spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:sql/schema/*.sql
    data: classpath:sql/data/*.sql
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  h2:
    console:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.jiang.unit.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
